tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/dupes'

brew 'bash'
brew 'zsh'
brew 'zsh-completions'

brew 'coreutils'

brew 'awscli'
brew 'git'
brew 'hub'

brew 'mas'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'trash'
brew 'wget'
brew 'postgresql'
brew 'redis'

cask 'alfred'
cask 'caffeine'
cask 'gpgtools'
cask 'iterm2'
cask 'slack'
cask 'atom'
cask 'transmit'
cask 'docker'
cask 'docker-toolbox'
cask 'virtualbox'
cask 'vagrant'
cask 'vagrant-manager'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlstephen'

# Fonts
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'

mas '1Password', id: 443987910
mas 'Giphy Capture', id: 668208984
mas 'Sketch', id: 402476602
